quarkus.devservices.enabled=false

# Disable datasource
quarkus.datasource.enabled=false

# Disable Hibernate ORM
quarkus.hibernate-orm.enabled=false

# Disable JPA
quarkus.jpa.enabled=false

# Disable all extensions
quarkus.extensions.enabled=false

#http.proxyHost=127.0.0.1
#http.proxyPort=3128
#http.noProxy=google.it

camel.beans.http1=#class:org.apache.camel.component.http.HttpComponent


quarkus.http-client.proxy-host=127.0.0.1
quarkus.http-client.proxy-port=3128
#quarkus.http-client.non-proxy-hosts=localhost,*.example.com
