quarkus.devservices.enabled=false

# Disable datasource
quarkus.datasource.enabled=false

# Disable Hibernate ORM
quarkus.hibernate-orm.enabled=false

# Disable JPA
quarkus.jpa.enabled=false

# Disable all extensions
quarkus.extensions.enabled=false

# Enable message history
camel.context.message-history = true

camel.main.global-options[CamelMessageHistoryHeaderFormat] = %-40s %-30s %-120s %-12s
camel.main.global-options[CamelMessageHistoryOutputFormat] = %-40.40s %-30.30s %-290.290s %12.12s